### ISSUE TITLE
Inappropriate file naming convention used.

### ISSUE THREAD

**Issue by kanishkamakhija** [skyerofficial/tribute-page-the-nemesis#9]
File and folder naming conventions are key to maintaining a well-organized directory and drive structures.  Benefits of consistent file and folder naming are:
- Files are easily distinguished one from another.
- File names are easier to browse.

When a connection is made to a website without specifying a specific file in the URL, most servers return a default page. This page is known as the "landing page" and most servers will provide by default a file named "index.html" Thus, a connection made to "http://mysite.com"  serves "http://mysite.com/index.html".

Generally, a server can be configured to use a different file as a landing page if desired, but "index.html" is the most common and typically the name used unless the developer or administrator has a reason to configure the server otherwise.

**Comment by sakshya73** [comment]
Done
